// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsnenwabnidthqdnfmqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzbmVud2FibmlkdGhxZG5mbXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMTE1ODUsImV4cCI6MjA2Mzg4NzU4NX0.XXwQ_w0229F18hnEoQGrxc7-ahSl6SbXtoMnTR6ncoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);